apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: application-ns
stringData:
  SPRING_DATA_MONGODB_URI: mongodb://admin:200labanya@mongodb-headless-service.database.svc.cluster.local:27017/
  SPRING_DATA_MONGODB_DB_NAME: SOCIAL_DB